# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: aiko-chan-ai.DiscordBotClient
PackageVersion: 3.8.0
PackageLocale: en-US
Publisher: aiko-chan-ai
PublisherUrl: https://aiko-chan-ai.github.io/
PublisherSupportUrl: https://github.com/aiko-chan-ai/DiscordBotClient/issues
PackageName: DiscordBotClient
PackageUrl: https://github.com/aiko-chan-ai/DiscordBotClient
License: GPL-3.0
LicenseUrl: https://github.com/aiko-chan-ai/DiscordBotClient/blob/HEAD/LICENSE
Copyright: Copyright © 2024 @elysia.dev
ShortDescription: A patched version of Discord, with bot login support (and Vencord)
Moniker: discord-bot-client
Tags:
- css
- discord
- discord-api
- discord-bot
- discord-bot-client
- discord-client
- html
- javascript
- nodejs
ReleaseNotes: |-
  🛠️ Chores
  - Application Name: Renamed from DiscordBotClient to Nekocord
  - CI/CD: Added pipeline to run ESLint checks
  ✨ Features & Improvements
  - Discord Core: Updated to Stable 453248 (0a497ab)
  - Vencord: Updated to v1.13.1
  - Message Search API: Discord officially supports it for bots
  - Audio Quality: Allows sending audio at higher quality than the Voice Channel limit (#284)
  - Per-server Profiles: Added server-specific profile modification (#285)
  🐛 Fixes
  - App Reload: Prevented automatic use of latest build on reload (which caused crashes)
  - Slash Commands: Fixed some commands not showing in DM Channel (#282)
  📝 Refactors
  - Codebase: Fully refactored to TypeScript
  - Database: Replaced LevelDB with IndexedDB
  📝 Notes
  - Bugs fixed 🐛
  - Probably added more bugs to fix later 🎉
  What's Changed
  - Fixed grammar and improved wording by @FelOtt in #273
  - skip clone vencord if already cloned by @uukelele-scratch in #275
  - TypeScript rewrite by @aiko-chan-ai in #288
  New Contributors
  - @FelOtt made their first contribution in #273
  - @uukelele-scratch made their first contribution in #275
  Full Changelog: v3.7.4...v3.8.0
ReleaseNotesUrl: https://github.com/aiko-chan-ai/DiscordBotClient/releases/tag/v3.8.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
